import Head from "next/head";
import { useEffect } from "react";
import axiosInstance from "@/apis";
import {  useTheme } from "@mui/material";
import TextField from "@/components/TextField";

export default function Home() {

  const theme = useTheme()
  console.log("Home ~ theme:", theme)

  useEffect(() => {
    console.log("useEffect ~ process.env.BASE_URL:", process.env)

    axiosInstance.get('/users').then(res => console.log('res', res)
    ).catch(() => {})
  }, [])
  

  return (
    <>
      <Head>
        <title>Ecomerce Web</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
      <TextField id="outlined-basic" label="Outlined" variant="outlined" />
      </main>
    </>
  );
}
